# Site settings
title: KIPP Silo
email: chaid@kippchicago.org
description: "A ***REMOVED*** is 'a deep bin for storing material' as is KIPP Silo. KIPP Silo is the KIPP Network's Self-organized, Iterative, Late-binding (or lightweight), and Open-source (for now) data warehouse solution."
baseurl: ""
url: "http://kippdata.github.io/***REMOVED***"
twitter_username: chrishaid
github_username:  chrishaid

# Build settings
markdown: kramdown
permalink: pretty
