USE [NWEA]
GO

/****** Object:  Table [dbo].[AssessmentResults]    Script Date: 9/9/2015 9:27:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AssessmentResults$old_format](
	[TermName] [nvarchar](100) NULL,
	[StudentID] [nvarchar](100) NULL,
	[SchoolName] [nvarchar](100) NULL,
	[MeasurementScale] [nvarchar](100) NULL,
	[Discipline] [nvarchar](50) NULL,
	[GrowthMeasureYN] [nvarchar](5) NULL,
	[TestType] [nvarchar](50) NULL,
	[TestName] [nvarchar](100) NULL,
	[TestID] [int] NULL,
	[TestStartDate] [nvarchar](10) NULL,
	[TestDurationMinutes] [int] NULL,
	[TestRITScore] [int] NULL,
	[TestStandardError] [float] NULL,
	[TestPercentile] [int] NULL,
	[TypicalFallToFallGrowth] [float] NULL,
	[TypicalSpringToSpringGrowth] [float] NULL,
	[TypicalFallToSpringGrowth] [float] NULL,
	[TypicalFallToWinterGrowth] [float] NULL,
	[RITtoReadingScore] [nvarchar](4) NULL,
	[RITtoReadingMin] [nvarchar](4) NULL,
	[RITtoReadingMax] [nvarchar](4) NULL,
	[Goal1Name] [nvarchar](100) NULL,
	[Goal1RitScore] [float] NULL,
	[Goal1StdErr] [float] NULL,
	[Goal1Range] [nvarchar](7) NULL,
	[Goal1Adjective] [nvarchar](12) NULL,
	[Goal2Name] [nvarchar](100) NULL,
	[Goal2RitScore] [float] NULL,
	[Goal2StdErr] [float] NULL,
	[Goal2Range] [nvarchar](7) NULL,
	[Goal2Adjective] [nvarchar](12) NULL,
	[Goal3Name] [nvarchar](100) NULL,
	[Goal3RitScore] [float] NULL,
	[Goal3StdErr] [float] NULL,
	[Goal3Range] [nvarchar](7) NULL,
	[Goal3Adjective] [nvarchar](12) NULL,
	[Goal4Name] [nvarchar](100) NULL,
	[Goal4RitScore] [float] NULL,
	[Goal4StdErr] [float] NULL,
	[Goal4Range] [nvarchar](7) NULL,
	[Goal4Adjective] [nvarchar](12) NULL,
	[Goal5Name] [nvarchar](100) NULL,
	[Goal5RitScore] [float] NULL,
	[Goal5StdErr] [float] NULL,
	[Goal5Range] [nvarchar](7) NULL,
	[Goal5Adjective] [nvarchar](12) NULL,
	[Goal6Name] [nvarchar](100) NULL,
	[Goal6RitScore] [float] NULL,
	[Goal6StdErr] [float] NULL,
	[Goal6Range] [nvarchar](7) NULL,
	[Goal6Adjective] [nvarchar](12) NULL,
	[Goal7Name] [nvarchar](100) NULL,
	[Goal7RitScore] [float] NULL,
	[Goal7StdErr] [float] NULL,
	[Goal7Range] [nvarchar](7) NULL,
	[Goal7Adjective] [nvarchar](12) NULL,
	[Goal8Name] [nvarchar](100) NULL,
	[Goal8RitScore] [float] NULL,
	[Goal8StdErr] [float] NULL,
	[Goal8Range] [nvarchar](7) NULL,
	[Goal8Adjective] [nvarchar](12) NULL,
	[TestStartTime] [nvarchar](8) NULL,
	[PercentCorrect] [int] NULL,
	[ProjectedProficiency] [nvarchar](20) NULL
) ON [PRIMARY]

GO

INSERT INTO [dbo].[AssessmentResults$old_format]
SELECT 	[TermName],
	[StudentID],
	[SchoolName],
	[MeasurementScale],
	[Discipline],
	[GrowthMeasureYN],
	[TestType],
	[TestName],
	[TestID],
	[TestStartDate],
	[TestDurationMinutes],
	[TestRITScore],
	[TestStandardError],
	[TestPercentile],
	[TypicalFallToFallGrowth],
	[TypicalSpringToSpringGrowth],
	[TypicalFallToSpringGrowth],
	[TypicalFallToWinterGrowth],
	[RITtoReadingScore],
	[RITtoReadingMin],
	[RITtoReadingMax],
	[Goal1Name],
	[Goal1RitScore],
	[Goal1StdErr],
	[Goal1Range],
	[Goal1Adjective],
	[Goal2Name],
	[Goal2RitScore],
	[Goal2StdErr],
	[Goal2Range],
	[Goal2Adjective],
	[Goal3Name],
	[Goal3RitScore],
	[Goal3StdErr],
	[Goal3Range],
	[Goal3Adjective],
	[Goal4Name],
	[Goal4RitScore],
	[Goal4StdErr],
	[Goal4Range],
	[Goal4Adjective],
	[Goal5Name],
	[Goal5RitScore],
	[Goal5StdErr],
	[Goal5Range],
	[Goal5Adjective],
	[Goal6Name],
	[Goal6RitScore],
	[Goal6StdErr],
	[Goal6Range],
	[Goal6Adjective],
	[Goal7Name],
	[Goal7RitScore],
	[Goal7StdErr],
	[Goal7Range],
	[Goal7Adjective],
	[Goal8Name],
	[Goal8RitScore],
	[Goal8StdErr],
	[Goal8Range],
	[Goal8Adjective],
	[TestStartTime],
	[PercentCorrect],
	[ProjectedProficiency]
FROM [dbo].[AssessmentResults];
GO


--SELECT SUM(CAST(PercentCorrect AS int)) FROM AssessmentResults
--SELECT SUM(TestRITScore) FROM AssessmentResults$old_format;

DROP TABLE [dbo].[AssessmentResults]
GO

CREATE TABLE [dbo].[AssessmentResults](
	[TermName] [nvarchar](100) NULL,
	[StudentID] [nvarchar](100) NULL,
	[SchoolName] [nvarchar](100) NULL,
	[MeasurementScale] [nvarchar](100) NULL,
	[Discipline] [nvarchar](50) NULL,
	[GrowthMeasureYN] [nvarchar](5) NULL,
	-- BEGIN norms and weeks identification columns
	[NormsReferenceData] [int],
	[WISelectedAYFall] [int],
	[WISelectedAYWinter] [int],
	[WISelectedAYSpring] [int],
	[WIPreviousAYFall] [int],
	[WIPreviousAYWinter] [int],
	[WIPreviousAYSpring] [int],
	-- END new norms and weeks identification columns
	[TestType] [nvarchar](50) NULL,
	[TestName] [nvarchar](100) NULL,
	[TestID] [int] NULL,
	[TestStartDate] [nvarchar](10) NULL,
	[TestDurationMinutes] [int] NULL,
	[TestRITScore] [int] NULL,
	[TestStandardError] [float] NULL,
	[TestPercentile] [int] NULL,
	-- BEGIN new growth colums
	-- Fall-to-Fall
	[FalltoFallProjectedGrowth] [float] NULL,
	[FalltoFallObservedGrowth] [float] NULL,
	[FalltoFallObservedGrowthSE]  [float] NULL,
	[FalltoFallMetProjectedGrowth] [nvarchar](4) NULL,
	[FalltoFallConditionalGrowthIndex] [float] NULL,
	[FalltoFallConditionalGrowthPercentile] [float] NULL,
	-- Fall-to-Winter
	[FalltoWinterProjectedGrowth] [float] NULL,
	[FalltoWinterObservedGrowth] [float] NULL,
	[FalltoWinterObservedGrowthSE]  [float] NULL,
	[FalltoWinterMetProjectedGrowth] [nvarchar](4) NULL,
	[FalltoWinterConditionalGrowthIndex] [float] NULL,
	[FalltoWinterConditionalGrowthPercentile] [float] NULL,
	-- Fall-to-Spring
	[FalltoSpringProjectedGrowth] [float] NULL,
	[FalltoSpringObservedGrowth] [float] NULL,
	[FalltoSpringObservedGrowthSE]  [float] NULL,
	[FalltoSpringMetProjectedGrowth] [nvarchar](4) NULL,
	[FalltoSpringConditionalGrowthIndex] [float] NULL,
	[FalltoSpringConditionalGrowthPercentile] [float] NULL,
	-- Winter-to-Winter 
	[WintertoWinterProjectedGrowth] [float] NULL,
	[WintertoWinterObservedGrowth] [float] NULL,
	[WintertoWinterObservedGrowthSE]  [float] NULL,
	[WintertoWinterMetProjectedGrowth] [nvarchar](4) NULL,
	[WintertoWinterConditionalGrowthIndex] [float] NULL,
	[WintertoWinterConditionalGrowthPercentile] [float] NULL,
	-- Winter-to-Spring
	[WintertoSpringProjectedGrowth] [float] NULL,
	[WintertoSpringObservedGrowth] [float] NULL,
	[WintertoSpringObservedGrowthSE]  [float] NULL,
	[WintertoSpringMetProjectedGrowth] [nvarchar](4) NULL,
	[WintertoSpringConditionalGrowthIndex] [float] NULL,
	[WintertoSpringConditionalGrowthPercentile] [float] NULL,
	-- Spring-to-Spring
	[SpringtoSpringProjectedGrowth] [float] NULL,
	[SpringtoSpringObservedGrowth] [float] NULL,
	[SpringtoSpringObservedGrowthSE]  [float] NULL,
	[SpringtoSpringMetProjectedGrowth] [nvarchar](4) NULL,
	[SpringtoSpringConditionalGrowthIndex] [float] NULL,
	[SpringtoSpringConditionalGrowthPercentile] [float] NULL,
	--END new growth Columns
	[RITtoReadingScore] [nvarchar](4) NULL,
	[RITtoReadingMin] [nvarchar](4) NULL,
	[RITtoReadingMax] [nvarchar](4) NULL,
	[Goal1Name] [nvarchar](100) NULL,
	[Goal1RitScore] [float] NULL,
	[Goal1StdErr] [float] NULL,
	[Goal1Range] [nvarchar](7) NULL,
	[Goal1Adjective] [nvarchar](12) NULL,
	[Goal2Name] [nvarchar](100) NULL,
	[Goal2RitScore] [float] NULL,
	[Goal2StdErr] [float] NULL,
	[Goal2Range] [nvarchar](7) NULL,
	[Goal2Adjective] [nvarchar](12) NULL,
	[Goal3Name] [nvarchar](100) NULL,
	[Goal3RitScore] [float] NULL,
	[Goal3StdErr] [float] NULL,
	[Goal3Range] [nvarchar](7) NULL,
	[Goal3Adjective] [nvarchar](12) NULL,
	[Goal4Name] [nvarchar](100) NULL,
	[Goal4RitScore] [float] NULL,
	[Goal4StdErr] [float] NULL,
	[Goal4Range] [nvarchar](7) NULL,
	[Goal4Adjective] [nvarchar](12) NULL,
	[Goal5Name] [nvarchar](100) NULL,
	[Goal5RitScore] [float] NULL,
	[Goal5StdErr] [float] NULL,
	[Goal5Range] [nvarchar](7) NULL,
	[Goal5Adjective] [nvarchar](12) NULL,
	[Goal6Name] [nvarchar](100) NULL,
	[Goal6RitScore] [float] NULL,
	[Goal6StdErr] [float] NULL,
	[Goal6Range] [nvarchar](7) NULL,
	[Goal6Adjective] [nvarchar](12) NULL,
	[Goal7Name] [nvarchar](100) NULL,
	[Goal7RitScore] [float] NULL,
	[Goal7StdErr] [float] NULL,
	[Goal7Range] [nvarchar](7) NULL,
	[Goal7Adjective] [nvarchar](12) NULL,
	[Goal8Name] [nvarchar](100) NULL,
	[Goal8RitScore] [float] NULL,
	[Goal8StdErr] [float] NULL,
	[Goal8Range] [nvarchar](7) NULL,
	[Goal8Adjective] [nvarchar](12) NULL,
	[TestStartTime] [nvarchar](8) NULL,
	[PercentCorrect] [int] NULL,
	-- BEGIN new projected proficieny columns
	[ProjectedProficiencyStudy1] [nvarchar](20),
	[ProjectedProficiencyLevel1] [nvarchar](20),
	[ProjectedProficiencyStudy2] [nvarchar](20),
	[ProjectedProficiencyLevel2] [nvarchar](20),
	[ProjectedProficiencyStudy3] [nvarchar](20),
	[ProjectedProficiencyLevel3] [nvarchar](20)
	-- END new projected proficieny columns
) ON [PRIMARY]

GO

INSERT INTO [dbo].[AssessmentResults]
	([TermName],
	[StudentID],
	[SchoolName],
	[MeasurementScale],
	[Discipline],
	[GrowthMeasureYN],
	[TestType],
	[TestName],
	[TestID],
	[TestStartDate],
	[TestDurationMinutes],
	[TestRITScore],
	[TestStandardError],
	[TestPercentile],
	-- BEGIN new growth colums
	-- Fall-to-Fall old is [TypicalFallToFallGrowth]
	[FalltoFallProjectedGrowth],
	-- Fall-to-Winter old is [TypicalFallToWinterGrowth],
	[FalltoWinterProjectedGrowth],
	-- Fall-to-Spring old is [TypicalFallToSpringGrowth],
	[FalltoSpringProjectedGrowth],
	-- Spring-to-Spring old is [TypicalSpringToSpringGrowth],
	[SpringtoSpringProjectedGrowth],
	--END new growth Columns
	[RITtoReadingScore],
	[RITtoReadingMin],
	[RITtoReadingMax],
	[Goal1Name],
	[Goal1RitScore],
	[Goal1StdErr],
	[Goal1Range],
	[Goal1Adjective],
	[Goal2Name],
	[Goal2RitScore],
	[Goal2StdErr],
	[Goal2Range],
	[Goal2Adjective],
	[Goal3Name],
	[Goal3RitScore],
	[Goal3StdErr],
	[Goal3Range],
	[Goal3Adjective],
	[Goal4Name],
	[Goal4RitScore],
	[Goal4StdErr],
	[Goal4Range],
	[Goal4Adjective],
	[Goal5Name],
	[Goal5RitScore],
	[Goal5StdErr],
	[Goal5Range],
	[Goal5Adjective],
	[Goal6Name],
	[Goal6RitScore],
	[Goal6StdErr],
	[Goal6Range],
	[Goal6Adjective],
	[Goal7Name],
	[Goal7RitScore],
	[Goal7StdErr],
	[Goal7Range],
	[Goal7Adjective],
	[Goal8Name],
	[Goal8RitScore],
	[Goal8StdErr],
	[Goal8Range],
	[Goal8Adjective],
	[TestStartTime],
	[PercentCorrect],
	-- BEGIN new projected proficieny columns
	[ProjectedProficiencyLevel1]
	)
SELECT 	[TermName],
	[StudentID],
	[SchoolName],
	[MeasurementScale],
	[Discipline],
	[GrowthMeasureYN],
	[TestType],
	[TestName],
	[TestID],
	[TestStartDate],
	[TestDurationMinutes],
	[TestRITScore],
	[TestStandardError],
	[TestPercentile],
	[TypicalFallToFallGrowth],
	[TypicalFallToWinterGrowth],
	[TypicalFallToSpringGrowth],
	[TypicalSpringToSpringGrowth],
	[RITtoReadingScore],
	[RITtoReadingMin],
	[RITtoReadingMax],
	[Goal1Name],
	[Goal1RitScore],
	[Goal1StdErr],
	[Goal1Range],
	[Goal1Adjective],
	[Goal2Name],
	[Goal2RitScore],
	[Goal2StdErr],
	[Goal2Range],
	[Goal2Adjective],
	[Goal3Name],
	[Goal3RitScore],
	[Goal3StdErr],
	[Goal3Range],
	[Goal3Adjective],
	[Goal4Name],
	[Goal4RitScore],
	[Goal4StdErr],
	[Goal4Range],
	[Goal4Adjective],
	[Goal5Name],
	[Goal5RitScore],
	[Goal5StdErr],
	[Goal5Range],
	[Goal5Adjective],
	[Goal6Name],
	[Goal6RitScore],
	[Goal6StdErr],
	[Goal6Range],
	[Goal6Adjective],
	[Goal7Name],
	[Goal7RitScore],
	[Goal7StdErr],
	[Goal7Range],
	[Goal7Adjective],
	[Goal8Name],
	[Goal8RitScore],
	[Goal8StdErr],
	[Goal8Range],
	[Goal8Adjective],
	[TestStartTime],
	[PercentCorrect],
	[ProjectedProficiency]
FROM [dbo].[AssessmentResults$old_format];
GO

-- Update some new columns 


--SELECT COUNT(*) FROM [dbo].AssessmentResults$old_format
--SELECT COUNT(*) FROM [dbo].AssessmentResults

--SELECT SUM(TestRITScore) FROM [dbo].AssessmentResults$old_format
--SELECT SUM(TestRITScore) FROM [dbo].AssessmentResults

--SELECT SUM([TypicalSpringToSpringGrowth]) FROM [dbo].AssessmentResults$old_format
--SELECT SUM([SpringtoSpringProjectedGrowth]) FROM [dbo].AssessmentResults
